#!/usr/bin/env sh

_vim () {
    file="$1"
    shift 1
    VIMINIT='' command vim \
        --clean -u DEFAULTS -U NONE -i NONE \
        --not-a-term -esc \
        "$@" \
        +quit \
        "$file" 2> /dev/null
}

sgr () {
    printf "\033[%sm%s\033[0m" "$1" "$2"
}

gen_diffprg () {
    diffprg="$(mktemp)"
    echo '
    #!/usr/bin/env sh

    diff -d "$@"
    ' > "$diffprg"
    chmod +x "$diffprg"
    echo "$diffprg"
}

diff3_get_ed_patch () {
    diffprg="$1"
    shift 1
    diff3 -x --diff-program="$diffprg" "$1" "$2" "$3" 2> /dev/null
}

git_get_filenames () {
    git diff --diff-filter=ARMC --name-status "$1" "$2" | cut -f2-
}

get_filetype_vim () {
    _vim "$1" \
        +'sil! echo "no idea why this echo is needed' \
        +'sil! exec "!echo ".&ft'
}

git_get_formatter () {
    ft="$(get_filetype_vim "$1")"
    [ -z "$ft" ] && return

    if [ -e ".gitconfig" ]; then
        fmtprg="$(git config --file=.gitconfig --get stylecheck."$ft")"
        if [ -n "$fmtprg" ]; then
            echo "$fmtprg"
            return
        fi
    fi

    git config --get stylecheck."$ft"
}

git_retrieve () {
    obj="$1"
    file="$2"
    out="$3"

    git show "$obj":"$file" 2> /dev/null > "$out"
    ret="$?"
    [ "$ret" != 0 ] && echo > "$out"
    return "$ret"
}

vim_apply_patch () {
    in="$1"
    out="$2"
    patch="$3"
    _vim "$in" \
        -e \
        -S "$patch" \
        +"write! $out"
}

git_display_diff () {
    git diff --color "$cur" "$new" | sed '
        /diff /,/@@/ {
            H;/@@/!d;z;x
            s|.*\n.*--- a/[^\n]*.*+++ b/[^\n]*|==> '"$(sgr 1 "$cur_name")"'|
        }'
}

process_file () {
    obj1="$1"
    obj2="$2"
    line="$3"
    diffprg="$4"

    old_name="$(echo "$line" | cut -f1)"
    cur_name="$(echo "$line" | cut -f2)"
    [ -z "$cur_name" ] && cur_name="$old_name"

    formatter="$(git_get_formatter "$cur_name")"

    if [ -z "$formatter" ]; then
        return
    fi

    tempdir="$(mktemp -d)"

    old="$tempdir"/old
    cur="$tempdir"/cur
    new="$tempdir"/new
    patch="$tempdir"/patch

    git_retrieve "$obj2" "$cur_name" "$cur"
    git_retrieve "$obj1" "$old_name" "$old"

    eval "$formatter" "$cur" > "$new" 2> /dev/null

    if diff -s "$cur" "$new" > /dev/null; then
        return
    fi

    diff3_get_ed_patch "$diffprg" "$cur" "$old" "$new" > "$patch"

    if [ -s "$patch" ]; then
        vim_apply_patch "$cur" "$new" "$patch"
        display_diff "$cur" "$new"
    fi

    rm "$old" "$cur" "$new" "$patch"
    rmdir "$tempdir"
}

main () {
    obj1="$1"
    obj2="$2"

    if [ -z "$obj1" ] || [ -z "$obj2" ]; then
        return 1
    fi

    diffprg="$(gen_diffprg)"

    git_get_filenames "$obj1" "$obj2" | while read -r line; do
        process_file "$obj1" "$obj2" "$line" "$diffprg"
    done

    rm "$diffprg"
}

main "$@"
