#!/usr/bin/env sh
# SPDX-License-Identifier:  MIT
# Copyright 2023 Jorengarenar

g_no_term=
g_use_color=

diff3_get_ed_patch () (
    diffprg="$1"
    shift 1
    if [ -s "$2" ] && ! diff -s "$2" "$3" > /dev/null; then
        diff3 -x --diff-program="$diffprg" "$1" "$2" "$3" 2> /dev/null
    else
        "$diffprg" --ed "$1" "$3"
    fi
)

gen_diffprg () (
    diffprg="$(mktemp)"
    echo '
    #!/usr/bin/env sh

    diff -d "$@"
    ' > "$diffprg"
    chmod +x "$diffprg"
    echo "$diffprg"
)

git_get_conf () (
    var="$1"

    repo_root="$(git rev-parse --show-toplevel)"
    if [ -n "$repo_root" ] && [ -e "$repo_root"/.gitstylecheck ]; then
        val="$(git config --file="$repo_root"/.gitstylecheck --get "$var")"
        if [ -n "$val" ]; then
            echo "$val"
            return
        fi
    fi

    git config --get "$var"
)

git_get_diffs () (
    cur="$1"
    new="$2"
    filename="$3"

    [ "$g_use_color" = 1 ] && color="--color" || color=

    # shellcheck disable=SC2086
    git diff $color "$cur" "$new" | \
        sed \
            -e "s/$(sed_esc -p "a$cur")/$(sed_esc -s "a/$filename")/g" \
            -e "s/$(sed_esc -p "b$new")/$(sed_esc -s "b/$filename")/g"
)

git_get_filenames () (
    # shellcheck disable=SC2086
    git diff --diff-filter=ARMC --name-status $1 $2 | cut -f2-
)

git_get_formatter () (
    ft="$(vim_get_filetype "$1")"
    [ -z "$ft" ] && return
    prg="$(git_get_conf stylecheck."$ft".fmtprg)"
    if [ -z "$prg" ]; then
        prg="$(git_get_conf stylecheck."$ft")"
    fi
    echo "$prg"
)

git_get_pager () (
    if [ -t 1 ]; then
        echo "cat"
        return
    fi

    pgr="$(git_get_conf pager.stylecheck)"
    if [ -z "$pgr" ]; then
        pgr="$(git_get_conf pager.diff)"
        if [ -z "$pgr" ]; then
            pgr="$(git env GIT_PAGER)"
            if [ -z "$pgr" ]; then
                pgr="less"
            fi
        fi
    fi

    echo "$pgr"
)

git_retrieve_file () (
    obj="$1"
    file="$2"
    out="$3"

    if [ -n "$obj" ]; then
        git show "$obj":"$file" 2> /dev/null > "$out"
    elif [ -e "$file" ]; then
        cat "$file" > "$out"
    fi
    ret="$?"
    [ "$ret" != 0 ] && printf "" > "$out"
    return "$ret"
)

vim_apply_patch () (
    in="$1"
    out="$2"
    patch="$3"
    vim -u NONE -es \
        -S "$patch" \
        +"w! $out" \
        +"quit!" \
        "$in"
)

vim_get_filetype () (
    vim --clean -es \
        +'exec "!echo ".&ft' \
        +"quit!" \
        "$1"
)

process_file () (
    obj1="$1"
    obj2="$2"
    line="$3"
    diffprg="$4"
    outfile="$5"

    old_name="$(echo "$line" | cut -f1)"
    cur_name="$(echo "$line" | cut -f2)"
    [ -z "$cur_name" ] && cur_name="$old_name"

    formatter="$(git_get_formatter "$cur_name")"

    if [ -z "$formatter" ]; then
        return
    fi

    if [ ! -x "$(command -v "${formatter%% *}")" ]; then
        warn "format program '${formatter%% *}\` not found"
        return
    fi

    tempdir="$(mktemp -d)"

    old="$tempdir"/old
    cur="$tempdir"/cur
    new="$tempdir"/new
    patch="$tempdir"/patch

    git_retrieve_file "$obj2" "$cur_name" "$cur"
    git_retrieve_file "$obj1" "$old_name" "$old"

    eval "$formatter" "$cur" > "$new" 2> /dev/null

    if diff -s "$cur" "$new" > /dev/null; then
        return
    fi

    diff3_get_ed_patch "$diffprg" "$cur" "$old" "$new" > "$patch"

    if [ -s "$patch" ]; then
        vim_apply_patch "$cur" "$new" "$patch"
        git_get_diffs "$cur" "$new" "$cur_name" >> "$outfile"
    fi

    rm "$old" "$cur" "$new" "$patch"
    rmdir "$tempdir"
)

sed_esc () (
    if [ "$1" = "-p" ]; then
        printf '%s\n' "$2" | sed -e 's/[]\/$*.^[]/\\&/g'
    elif [ "$1" = "-s" ]; then
        printf '%s\n' "$2" | sed -e 's/[\/&]/\\&/g'
    fi
)

usage () (
    true # TODO
)

warn () (
    >&2 printf "%s: " "$(basename "$0")"
    # printf "\033[30m\033[103m"
    >&2 echo "$@"
    # printf "\033[0m"
)


parse_options () {
    while :; do
        case $1 in
            -h)
                usage
                exit
                ;;
            --help)
                man "$0"
                exit
                ;;
            --color)
                g_use_color=1
                ;;
            --no-color)
                g_use_color=0
                ;;
            --)
                g_obj1="$2"
                g_obj2="$3"
                break
                ;;
            -?*)
                warn "unknown option: $1"
                usage
                exit 1
                ;;
            *)
                [ -z "$g_obj1" ] && g_obj1="$1" && break
                [ -z "$g_obj2" ] && g_obj2="$1" && break
                warn "ignored object: $1"
                break
        esac

        shift
    done

    if [ -z "$g_use_color" ] && [ "$g_no_term" = 0 ]; then
        g_use_color=1
    fi
}

main () (
    obj1="${1:-HEAD}"
    obj2="$2"

    diffprg="$(gen_diffprg)"
    outfile="$(mktemp)"

    git_get_filenames "$obj1" "$obj2" | while read -r line; do
        process_file "$obj1" "$obj2" "$line" "$diffprg" "$outfile"
    done

    if [ "$g_no_term" = 0 ]; then
        eval "cat '$outfile' | $(git_get_pager)"
    else
        cat "$outfile"
    fi

    rm "$diffprg" "$outfile"
)


[ -t 1 ] && g_no_term=0 || g_no_term=1

g_obj1=
g_obj2=
parse_options "$@"
main "$g_obj1" "$g_obj2"
